### ISSUE TITLE
events:KeyError: 65513

### ISSUE THREAD

**Issue by huooyk** [los-cocos/cocos#240] opened 2015-05-24 10:31 UTC
I am run samples/handling_events.py,If the input Alt + Alt,Will get it

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "D:\Python27\lib\site-packages\pyglet\window\win32\__init__.py", line 849, in _wnd_proc
    result = event_handler(msg, wParam, lParam)
  File "D:\Python27\lib\site-packages\pyglet\window\win32\__init__.py", line 918, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "D:\Python27\lib\site-packages\pyglet\window\__init__.py", line 1219, in dispatch_event
    EventDispatcher.dispatch_event(self, *args)
  File "D:\Python27\lib\site-packages\pyglet\event.py", line 340, in dispatch_event
    if handler(*args):
  File "C:\Users\Administrator.AJ1LBLNJX2GI2QO\workspace\MyGame\src\1hello.py", line 25, in on_key_release
    self.key_pressed.remove(key)
KeyError: 65513

**Comment by ccanepa** [comment] 2015-05-26 03:55
It is pressing Left Alt at the same time than Right Alt what gives trouble ?
Two consecutive Left (or Right) Alt press ?

You say the problem is in samples/handling_events.py but the traceback says the problem is found in a script 1hello.py   ??

FYI running samples/handling_events.py here and playings with the alt keys does not crash.
python 2.7, pyglet from bictbucket, both win 7/32 and xp/32 

What happens if you run the pyglet example https://bitbucket.org/pyglet/pyglet/src/4d5a39b03467e01702aa9efd22c529690878abe9/examples/events.py?at=default

?

**Comment by huooyk** [comment] 2015-06-08 17:39
sorry ,I underestimated your attention, I focus on the pyglet.I can't repeat mistake, but certain is 1. Hello. Py is a replica.
Try to press CTRL and move the mouse at the same time, get exceptions such as random
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "_build\bdist.win32\egg\pyglet\window\win32\__init__.py", line 617, in f
    
  File "_build\bdist.win32\egg\pyglet\window\win32\__init__.py", line 688, in _event_key
    
  File "_build\bdist.win32\egg\pyglet\window\__init__.py", line 1155, in dispatch_event
    
  File "_build\bdist.win32\egg\pyglet\event.py", line 355, in dispatch_event
  File "C:\Users\Administrator.AJ1LBLNJX2GI2QO\Desktop\cocos-samples\handling_events.py", line 58, in on_key_release
    self.keys_pressed.remove (key)
KeyError: 65508

**Comment by ccanepa** [comment] 2015-06-08 19:47
please update cocos to the last released or clone from this repo.
the issue is duplicate of #211, fixed at 2014 05 24 in master, or cocos >= 0.6.2  

The line 58 in handling_events.py in your traceback tells you are running near cocos 0.6.0 or older

**Closed by ccanepa** 2015-06-08 19:47 UTC
